name: searXng Sync
on:
  schedule:
    - cron:  '0 6 * * 1,4'
  workflow_dispatch:

jobs:
  searxng_sync:
    runs-on: ubuntu-latest
    steps:
      - uses: isahole/forks@main
        with:
          github_token: ${{ secrets.PAT }}
          #upstream_repository: searxng/searxng
          upstream_repository: yellowhat/searx-heroku  
          target_repository: isahole/hk
          upstream_branch: searxng
          target_branch: searxng
          force: true
          tags: true
  searxng_push:
    needs: searxng_sync
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: searxng
      - run: |
          rm -rf .github
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "$(date "+%Y%m%d-%H%M")"
          git push
